version: '3'
services:
  consul:
    image: consul:0.9.0
    ports:
    - 8500:8500

  linkerd:
    image: buoyantio/linkerd:1.1.2
    command: /config.yaml
    volumes:
    - ./linkerd/linkerd.conf.yaml:/config.yaml
    ports:
      - 9990:9990
      - 4140:4140
      - 4141:4141
    depends_on:
    - consul-registrator
    - zipkin
  
  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
    - 9410:9410
    environment:
    - SCRIBE_ENABLED=true 

  consul-registrator:
    image: gliderlabs/registrator:v7
    # This will work with dynamic ports
    command: -ip=docker.for.mac.localhost consul://consul:8500
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
    - consul

  server:
    image: alextanhongpin/echo
    ports:
    - 8080 # Ports cannot be dynamic?
    environment:
      - SERVICE_NAME=server
      - SERVICE_TAGS=dev
      - SERVICE_REGION=us2

  audit: 
    build: ./node/
    ports:
    - 8100
    environment:
      - SERVICE_NAME=audit
      - SERVICE_TAGS=dev
      - SERVICE_REGION=us2

  service:
    image: buoyantio/helloworld
    command: ["-addr=:7777", "-text=Hello"]
    ports:
      - 7777
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_REGION=us2
