version: '2'
services:
  consul:
    image: consul:0.9.0
    ports:
    - 8500:8500
    networks:
      lb:

  linkerd:
    image: buoyantio/linkerd:1.1.2
    command: /config.yaml
    links:
    - consul
    volumes:
    - ./linkerd/linkerd.conf.yaml:/config.yaml
    # - ./disco:/io.buoyant/disco
    ports:
      - 9990:9990
      - 4140:4140
    depends_on:
    - consul-registrator
    networks:
      lb:

  consul-registrator:
    image: gliderlabs/registrator:v7
    command: consul://consul:8500
    links:
    - consul
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
    - consul
    networks:
      lb:

  # Bad naming
  # Out of the box, linkerd is configured to listen on port 4140, and to route any HTTP calls with a Host header set to “web” to a service listening on port 9999.
  # web: 
  server:
    image: alextanhongpin/echo
    ports:
    - 8080 # Ports cannot be dynamic?
    environment:
      - SERVICE_NAME=server
      - SERVICE_TAGS=dev
      - SERVICE_REGION=us2
    # links:
    # - consul-registrator
    # - linkerd
    networks:
      lb:

  audit: 
    build: ./node/
    ports:
    - 8100:8100
    environment:
      - SERVICE_NAME=audit
      - SERVICE_TAGS=dev
      - SERVICE_REGION=us2
    networks:
      lb:

  service:
    image: buoyantio/helloworld
    command: ["-addr=:7777", "-text=Hello"]
    ports:
      - 7777:7777
    environment:
      # - SERVICE_NAME=service
      - SERVICE_TAGS=dev
      - SERVICE_REGION=us2
    networks:
      lb:

networks:
  lb: